// Code generated by Kitex v0.4.4. DO NOT EDIT.
package baseapiservice

import (
	server "github.com/cloudwego/kitex/server"
	tiktokbackendbase "github.com/demonwuwen/tiktokBackend/kitex_gen/tiktokBackendBase"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler tiktokbackendbase.BaseApiService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
