// Code generated by hertz generator.

package tiktokBackendBase

import (
	"context"

	tiktokBackendBase "Demonwuwen/tiktokBackend/cmd/api/biz/model/tiktokBackendBase"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UserRegister .
// @router /douyin/user/register [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.UserRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.UserRegisterResponse)

	c.JSON(consts.StatusOK, resp)
}

// UserLogin .
// @router /douyin/user/login [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.UserLoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.UserLoginResponse)

	c.JSON(consts.StatusOK, resp)
}

// UserGet .
// @router /douyin/user [GET]
func UserGet(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.UserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.UserResponse)

	c.JSON(consts.StatusOK, resp)
}

// PublishVideo .
// @router /douyin/publish/action [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.PublishActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.PublishActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// PublishList .
// @router /douyin/publish/list [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.PublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.PublishListResponse)

	c.JSON(consts.StatusOK, resp)
}

// Feed .
// @router /douyin/feed [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.FeedResponse)

	c.JSON(consts.StatusOK, resp)
}

// FavoriteAct .
// @router /douyin/favorite/action [POST]
func FavoriteAct(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.FavoriteActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.FavoriteActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// FavoriteList .
// @router /douyin/favorite/list [GET]
func FavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.FavoriteListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.FavoriteListResponse)

	c.JSON(consts.StatusOK, resp)
}

// CommentAct .
// @router /douyin/comment/action [POST]
func CommentAct(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.CommentActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.CommentActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// CommentList .
// @router /douyin/comment/list [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.CommentListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.CommentListResponse)

	c.JSON(consts.StatusOK, resp)
}

// RelationAct .
// @router /douyin/relation/action [POST]
func RelationAct(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.RelationActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.RelationActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// FowllowList .
// @router /douyin/relation/follower/list [GET]
func FowllowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.FollowListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.FollowListResponse)

	c.JSON(consts.StatusOK, resp)
}

// FowllowerList .
// @router /douyin/relation/follower/list [GET]
func FowllowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.FollowerListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.FollowerListResponse)

	c.JSON(consts.StatusOK, resp)
}

// FrientList .
// @router /douyin/relation/follower/list [GET]
func FrientList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req tiktokBackendBase.FriendListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(tiktokBackendBase.FriendListResponse)

	c.JSON(consts.StatusOK, resp)
}
